### ISSUE TITLE
Figma Expirable Image Link was used in the website which is no longer loading

### ISSUE THREAD

**Issue by Saboor-Hakimi** [SulimanHakimi/Kunduz-Kabob-WebApp#3]
In the header of the website you have used an image from Figma which is an expirable temporary signed URL, the URL have expired and it's no longer loading that image resource, you should consider uploading that image somewhere else and include it from there in your source code.
![image](https://github.com/SulimanHakimi/Kunduz-Kabob-WebApp/assets/44523544/d9ad968b-b128-4487-848a-65df3b770c2a)
![image](https://github.com/SulimanHakimi/Kunduz-Kabob-WebApp/assets/44523544/7452ff21-f883-4e64-bb76-999186dc6f70)

**Comment by SulimanHakimi** [comment]
fixed
